const LANGUAGES = [
    { key: "ar", name: "العربية", flag: "https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/dz.svg" },
    { key: "en", name: "English", flag: "https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/gb.svg" },
    { key: "fr", name: "Français", flag: "https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/fr.svg" },
    { key: "id", name: "Bahasa Indonesia", flag: "https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/id.svg" },
    { key: "ja", name: "日本語", flag: "https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/jp.svg" }
];

const TRANSLATIONS = {
    ar: {
        gameTitle: "مطابقة حيوانات وألوان",
        restartBtn: "إعادة اللعب",
        showAllBtn: "أظهر الكل 2 ث",
        playAgainBtn: "العب مرة أخرى",
        saveScoreBtn: "حفظ في لوحة الصدارة",
        usernameLabel: "اسم المستخدم:",
        victoryText: "أحسنت! انتهيت 🎉",
        finalTimeText: "الوقت:",
        leaderboard: "لوحة الصدارة",
        leaderboardFilter: "حجم الطاولة:",
        settingsTitle: "الإعدادات",
        themeLabel: "الثيم",
        audioLabel: "مستوى الصوت",
        typeLabel: "نوع البطاقات",
        sizeLabel: "حجم الطاولة",
        exitBtn: "خروج",
        animals: "حيوانات",
        colors: "ألوان",
        mixed: "مختلط",
        avatar: "الصورة",
        name: "الاسم",
        time: "الوقت",
        type: "النوع",
        saveBtn: "حفظ",
        saveToLeaderboardBtn: "حفظ في لوحة الصدارة",
        backBtn: "رجوع",
        toLeaderboardBtn: "لوحة الصدارة",
        boardSizes: ["2x2", "2x4", "4x4", "5x4", "5x5"],
        inputError: "يرجى كتابة اسم مناسب (2 أحرف على الأقل)",
        saveSuccess: "تم إضافة نتيجتك بنجاح!",
        saveUpdate: "تم تحديث نتيجتك الجديدة الأفضل!",
        saveNotUpdate: "لديك نتيجة أفضل بالفعل! لم يتم التحديث.",
        saveError: "خطأ في الاتصال بالسيرفر!"
    },
    en: {
        gameTitle: "Match Animals & Colors",
        restartBtn: "Restart Game",
        showAllBtn: "Show All 2s",
        playAgainBtn: "Play Again",
        saveScoreBtn: "Save to Leaderboard",
        usernameLabel: "Username:",
        victoryText: "Well Done! Finished 🎉",
        finalTimeText: "Time:",
        leaderboard: "Leaderboard",
        leaderboardFilter: "Board Size:",
        settingsTitle: "Settings",
        themeLabel: "Theme",
        audioLabel: "Sound Level",
        typeLabel: "Card Type",
        sizeLabel: "Board Size",
        exitBtn: "Exit",
        animals: "Animals",
        colors: "Colors",
        mixed: "Mixed",
        avatar: "Avatar",
        name: "Name",
        time: "Time",
        type: "Type",
        saveBtn: "Save",
        saveToLeaderboardBtn: "Save to Leaderboard",
        backBtn: "Back",
        toLeaderboardBtn: "Leaderboard",
        boardSizes: ["2x2", "2x4", "4x4", "5x4", "5x5"],
        inputError: "Please enter a valid name (at least 2 characters)",
        saveSuccess: "Your score added successfully!",
        saveUpdate: "Your new best score updated!",
        saveNotUpdate: "You already have a better score! Not updated.",
        saveError: "Server error!"
    },
    fr: {
        gameTitle: "Associer Animaux & Couleurs",
        restartBtn: "Recommencer",
        showAllBtn: "Tout Montrer 2s",
        playAgainBtn: "Jouer Encore",
        saveScoreBtn: "Sauver au classement",
        usernameLabel: "Nom d'utilisateur:",
        victoryText: "Bravo! Terminé 🎉",
        finalTimeText: "Temps:",
        leaderboard: "Classement",
        leaderboardFilter: "Taille du plateau:",
        settingsTitle: "Paramètres",
        themeLabel: "Thème",
        audioLabel: "Volume",
        typeLabel: "Type de cartes",
        sizeLabel: "Taille du plateau",
        exitBtn: "Quitter",
        animals: "Animaux",
        colors: "Couleurs",
        mixed: "Mixte",
        avatar: "Avatar",
        name: "Nom",
        time: "Temps",
        type: "Type",
        saveBtn: "Sauver",
        playAgainBtn: "Jouer Encore",
        saveToLeaderboardBtn: "Sauver au Classement",
        backBtn: "Retour",
        toLeaderboardBtn: "Classement",
        boardSizes: ["2x2", "2x4", "4x4", "5x4", "5x5"],
        inputError: "Entrez un nom valide (2 caractères au minimum)",
        saveSuccess: "Score ajouté avec succès!",
        saveUpdate: "Votre meilleur score est mis à jour!",
        saveNotUpdate: "Vous avez déjà un meilleur score! Non modifié.",
        saveError: "Erreur serveur!"
    },
    id: {
        gameTitle: "Cocokkan Hewan & Warna",
        restartBtn: "Mulai Ulang",
        showAllBtn: "Tampilkan Semua 2d",
        saveScoreBtn: "Simpan ke Papan Skor",
        usernameLabel: "Nama pengguna:",
        victoryText: "Bagus! Kamu Menang! 🎉",
        finalTimeText: "Waktu:",
        leaderboard: "Papan Skor",
        leaderboardFilter: "Ukuran papan:",
        settingsTitle: "Pengaturan",
        themeLabel: "Tema",
        audioLabel: "Volume",
        typeLabel: "Jenis kartu",
        sizeLabel: "Ukuran papan",
        exitBtn: "Keluar",
        animals: "Hewan",
        colors: "Warna",
        mixed: "Campuran",
        avatar: "Avatar",
        name: "Nama",
        time: "Waktu",
        type: "Jenis",
        saveBtn: "Simpan",
        playAgainBtn: "Main Lagi",
        saveToLeaderboardBtn: "Simpan ke Papan Skor",
        backBtn: "Kembali",
        toLeaderboardBtn: "Papan Skor",
        boardSizes: ["2x2", "2x4", "4x4", "5x4", "5x5"],
        inputError: "Masukkan nama yang valid (minimal 2 karakter)",
        saveSuccess: "Skor berhasil ditambahkan!",
        saveUpdate: "Skor terbaik baru diperbarui!",
        saveNotUpdate: "Anda sudah punya skor lebih baik! Tidak diperbarui.",
        saveError: "Kesalahan server!"
    },
    ja: {
        gameTitle: "動物と色をマッチ",
        restartBtn: "再スタート",
        showAllBtn: "全て表示 2秒",
        saveScoreBtn: "ランキングへ保存",
        usernameLabel: "ユーザー名：",
        victoryText: "おめでとう！クリア 🎉",
        finalTimeText: "時間：",
        leaderboard: "ランキング",
        leaderboardFilter: "盤サイズ：",
        settingsTitle: "設定",
        themeLabel: "テーマ",
        audioLabel: "音量",
        typeLabel: "カードタイプ",
        sizeLabel: "盤サイズ",
        exitBtn: "終了",
        animals: "動物",
        colors: "色",
        mixed: "ミックス",
        avatar: "アバター",
        name: "名前",
        time: "時間",
        type: "タイプ",
        saveBtn: "保存",
        playAgainBtn: "もう一度プレイ",
        saveToLeaderboardBtn: "ランキングへ保存",
        backBtn: "戻る",
        toLeaderboardBtn: "ランキング",
        boardSizes: ["2x2", "2x4", "4x4", "5x4", "5x5"],
        inputError: "有効な名前を入力してください（2文字以上）",
        saveSuccess: "スコアが追加されました！",
        saveUpdate: "新しいベストスコアに更新！",
        saveNotUpdate: "すでにより良いスコアがあります！未更新。",
        saveError: "サーバーエラー！"
    }
};
